source 'https://github.com/CocoaPods/Specs.git'

# App Targets
target 'DLVersion iOS', :exclusive => true do
  platform :ios, '6.0'

  pod "DLVersion", :path => "../"
end

target 'DLVersion watchOS Extension', :exclusive => true do
  platform :watchos, '2.0'

  pod "DLVersion", :path => "../"
end

target 'DLVersion tvOS', :exclusive => false do
  platform :tvos, '9.0'

  pod "DLVersion", :path => "../"
end

target 'DLVersion OS X', :exclusive => false do
  platform :osx, '10.9'

  pod "DLVersion", :path => "../"
end

# Framework Targets
target 'DLVersionIOS', :exclusive => true do
  platform :ios, '6.0'

  pod "DLVersion", :path => "../"
end

target 'DLVersionWatchOS', :exclusive => true do
  platform :watchos, '2.0'

  pod "DLVersion", :path => "../"
end

target 'DLVersionTVOS', :exclusive => true do
  platform :tvos, '9.0'

  pod "DLVersion", :path => "../"
end

target 'DLVersionOSX', :exclusive => true do
  platform :osx, '10.9'

  pod "DLVersion", :path => "../"
end

# Test Targets
target 'DLVersionIOSTests', :exclusive => true do
  platform :ios, '6.0'
  
  pod "DLVersion", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

target 'DLVersionTVOSTests', :exclusive => true do
  platform :tvos, '9.0'
  
  pod "DLVersion", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

target 'DLVersionOSXTests', :exclusive => true do
  platform :osx, '10.9'
  
  pod "DLVersion", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

# Hack to get around requiring Bitcode on tvOS.
# http://stackoverflow.com/a/34573451/105431
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.platform_name == :tvos || target.platform_name == :watchos then
      target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'YES'
      end
    end
  end
end 
