source 'https://github.com/CocoaPods/Specs.git'

target 'DLVersion', :exclusive => true do
  pod "DLVersion", :path => "../"
end

target 'DLVersionWatchOS', :exclusive => true do
  platform :watchos, '2.0'

  pod "DLVersion", :path => "../"
end

target 'DLVersionTVOS', :exclusive => true do
  platform :tvos, '9.0'

  pod "DLVersion", :path => "../"
end

target 'DLVersionOSX', :exclusive => true do
  platform :osx, '10.9'

  pod "DLVersion", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DLVersion", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

target 'DLVersionTVOSTests', :exclusive => true do
  platform :tvos, '9.0'
  
  pod "DLVersion", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

target 'DLVersionOSXTests', :exclusive => true do
  platform :osx, '10.9'
  
  pod "DLVersion", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

# Hack to get around requiring Bitcode on tvOS.
# http://stackoverflow.com/a/34573451/105431
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.platform_name == :tvos then
      target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'YES'
      end
    end
  end
end 
